# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md

imports:
    - { resource: indexes/ladder.yml }
    - { resource: indexes/identities.yml }
    - { resource: indexes/teams.yml }
    - { resource: indexes/summoner_names.yml }
    - { resource: indexes/members.yml }

fos_elastica:
    clients:
        default: { host: '%env(ELASTICA_HOST)%', port: '%env(ELASTICA_PORT)%' }
