framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    ide: phpstorm

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    validation: { enable_annotations: true }

    php_errors:
        log: '%kernel.debug%'
