knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        discord:
            type: discord
            client_id: '%env(OAUTH_DISCORD_ID)%'
            client_secret: '%env(OAUTH_DISCORD_SECRET)%'
            redirect_route:  app_core_oauth_discord_connectdiscordcheck
            redirect_params: {}
