lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/var/jwt/private.pem'
    public_key: '%kernel.project_dir%/var/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 604800 #1 semaine
