nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ORIGIN_LOLPROS)%', '%env(CORS_ORIGIN_LOCALHOST)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': null
