security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    encoders:
        App\Entity\Core\User\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Core\User\User
                property: username

    firewalls:
        login:
            pattern:  ^/auth/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /auth/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        refresh:
            pattern:  ^/auth/token/refresh
            stateless: true
            anonymous: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/auth/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/add-requests, methods: [POST], role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, methods: [POST, PUT, DELETE], roles: ROLE_USER }
