core_controllers:
    resource: ../../src/Controller/Core/
    type: annotation

league_controllers:
    resource: ../../src/Controller/LeagueOfLegends/
    type: annotation
    prefix: '/lol'

elasticsearch_controllers:
    resource: ../../src/Controller/ElasticSearch/
    type: annotation
    prefix: '/es'
