fos_elastica:
  indexes:
    lp_profiles:
      index_name: "lp_profiles"
      settings:
        number_of_replicas: 0
        number_of_shards: 1
        analysis:
          normalizer:
            lower:
              type: custom
              filter: [ "lowercase" ]
      types:
        profile:
          dynamic: strict
          properties:
            uuid:
            name:
              type: keyword
              normalizer: lower
            slug:
              type: keyword
            country:
            league_player:
              type: object
              properties:
                position:
                accounts:
                  type: nested
                  properties:
                    uuid:
                    profile_icon_id:
                    riot_id:
                    encrypted_riot_id:
                    smurf:
                    summoner_name:
                      type: keyword
                      normalizer: lower
                    summoner_names:
                      type: nested
                      properties:
                        name:
                        created_at:
                    rank:
                      type: nested
                      properties:
                        tier:
                        rank:
                        league_points:
                        wins:
                        losses:
                        score:
                        created_at:
                    peak:
                      type: nested
                      properties:
                        tier:
                        rank:
                        league_points:
                        wins:
                        losses:
                        score:
                        created_at:
                    season9:
                      type: nested
                      properties:
                        end:
                          type: nested
                          properties:
                            tier:
                            rank:
                            league_points:
                            wins:
                            losses:
                            score:
                            created_at:
                        peak:
                          type: nested
                          properties:
                            tier:
                            rank:
                            league_points:
                            wins:
                            losses:
                            score:
                            created_at:
                score:
                  type: integer
            staff:
              type: object
              properties:
                position:
            regions:
              type: nested
              properties:
                uuid:
                  type: keyword
                name:
                slug:
                shorthand:
                  type: keyword
                logo:
                  type: object
                  properties:
                    public_id:
                    version:
                    url:

            social_media:
              type: object
              properties:
                twitter:
                facebook:
                discord:
                twitch:
                leaguepedia:

          persistence:
            driver: orm
            model: App\Entity\Profile\Profile
            model_to_elastica_transformer:
              service: App\Transformer\ProfileTransformer
            listener:
              defer: true
              logger: true
