services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Fetcher\PlayerFetcher:
        arguments:
            $type: '@fos_elastica.index.lp_players'

    App\Fetcher\LadderFetcher:
        arguments:
            $type: '@fos_elastica.index.lp_ladder'

    App\Fetcher\SummonerNameFetcher:
        arguments:
            $type: '@fos_elastica.index.lp_summoner_names'

    App\Fetcher\TeamFetcher:
        arguments:
            $type: '@fos_elastica.index.lp_teams'

    App\Fetcher\MemberFetcher:
        arguments:
            $type: '@fos_elastica.index.lp_members'

    App\Fetcher\SearchFetcher:
        arguments:
            $type: '@fos_elastica.index.lp_players'

    App\Fetcher\RankingFetcher:
        arguments:
            $type: '@fos_elastica.index.lp_rankings'
