services:
    _defaults:
        autowire: true
        autoconfigure: true

    api.indexer.ladder:
        class: App\Indexer\Indexer
        arguments:
            - 'lp_ladder'
            - '@fos_elastica.index.lp_ladder'
            - '@App\Fetcher\LadderFetcher'
            - '@App\Transformer\LadderTransformer'

    api.indexer.identities:
        class: App\Indexer\Indexer
        arguments:
            - 'lp_identities'
            - '@fos_elastica.index.lp_identities'
            - '@App\Fetcher\IdentityFetcher'
            - '@App\Transformer\IdentityTransformer'

    api.indexer.summoner_names:
        class: App\Indexer\Indexer
        arguments:
            - 'lp_summoner_names'
            - '@fos_elastica.index.lp_summoner_names'
            - '@App\Fetcher\SummonerNameFetcher'
            - '@App\Transformer\SummonerNameTransformer'

    api.indexer.teams:
        class: App\Indexer\Indexer
        arguments:
            - 'lp_teams'
            - '@fos_elastica.index.lp_teams'
            - '@App\Fetcher\TeamFetcher'
            - '@App\Transformer\TeamTransformer'

    api.indexer.members:
        class: App\Indexer\Indexer
        arguments:
            - 'lp_members'
            - '@fos_elastica.index.lp_members'
            - '@App\Fetcher\MemberFetcher'
            - '@App\Transformer\MemberTransformer'
