services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Transformer\LadderTransformer: ~
    App\Transformer\IdentityTransformer: ~
    App\Transformer\SummonerNameTransformer: ~
    App\Transformer\TeamTransformer: ~
    App\Transformer\MemberTransformer: ~
